project_name: abx
release:
  github:
    owner: logan-bobo
    name: abx
builds:
  - id: abx
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/logan-bobo/abx/pkg/version.version=
archives:
  - id: abx
    builds:
    - abx
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
