apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: abx
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/logan-bobo/abx/releases/download/v0.1.0/abx_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./abx"
      to: "."
    - from: LICENSE
      to: "."
    bin: "abx"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/logan-bobo/abx/releases/download/v0.1.0/abx_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./abx"
      to: "."
    - from: LICENSE
      to: "."
    bin: "abx"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/logan-bobo/abx/releases/download/v0.1.0/abx_windows_amd64.zip
    sha256: ""
    files:
    - from: "/abx.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "abx.exe"
  shortDescription: A new plugin
  homepage: https://github.com/logan-bobo/abx
  caveats: |
    Usage:
      $ kubectl abx

    For additional options:
      $ kubectl abx --help
      or https://github.com/logan-bobo/abx/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
